const http = require('http');
const fs = require('fs');
const path = require('path');

// Function to run a test case
function runTest(language, code, input = undefined) {
  return new Promise((resolve, reject) => {
    // Request options
    const options = {
      hostname: 'localhost',
      port: 5000,
      path: '/api/compile',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      }
    };

    // Prepare the payload
    const payload = {
      code: code,
      language: language
    };
    
    // Only add input if it's defined
    if (input !== undefined) {
      payload.input = input;
    }
    
    console.log(`\nTesting ${language}${input ? ' with input' : ''}:`);
    console.log(JSON.stringify(payload, null, 2));
    
    // Make the request
    const req = http.request(options, (res) => {
      let data = '';
      
      res.on('data', (chunk) => {
        data += chunk;
      });
      
      res.on('end', () => {
        console.log('Response status:', res.statusCode);
        
        try {
          const parsedData = JSON.parse(data);
          
          // Handle PDF base64 content specially to avoid console flooding
          if (parsedData.pdfBase64) {
            const pdfBase64Preview = parsedData.pdfBase64.substring(0, 50) + '... (truncated)';
            console.log('Response body:', {
              ...parsedData,
              pdfBase64: pdfBase64Preview
            });
            
            // Save PDF to file for testing
            if (language === 'latex') {
              const pdfBuffer = Buffer.from(parsedData.pdfBase64, 'base64');
              const pdfPath = path.join(__dirname, 'test_output.pdf');
              fs.writeFileSync(pdfPath, pdfBuffer);
              console.log(`PDF saved to: ${pdfPath}`);
            }
          } else {
            console.log('Response body:', JSON.stringify(parsedData, null, 2));
          }
          
          resolve(parsedData);
        } catch (error) {
          console.error('Error parsing response:', data);
          reject(error);
        }
      });
    });

    req.on('error', (error) => {
      console.error('Request error:', error);
      reject(error);
    });

    // Write data to request body
    req.write(JSON.stringify(payload));
    req.end();
  });
}

// Run multiple test cases
async function runTests() {
  try {
    // Test JavaScript
    await runTest('js', 'console.log("Hello from JavaScript!");');
    
    // Test Python
    await runTest('python', 'print("Hello from Python!")');
    
    // Test Ruby
    await runTest('ruby', 'puts "Hello from Ruby!"');
    
    // Test with input
    await runTest('js', `
      const readline = require('readline');
      const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
      });
      
      rl.on('line', (line) => {
        console.log('You entered:', line);
        rl.close();
      });
    `, 'Hello from input!');
    
    // Test PHP
    await runTest('php', '<?php echo "Hello from PHP!\\n"; ?>');
    
    // Test C
    await runTest('c', `
      #include <stdio.h>
      
      int main() {
        printf("Hello from C!\\n");
        return 0;
      }
    `);
    
    // Test C++
    await runTest('cpp', `
      #include <iostream>
      
      int main() {
        std::cout << "Hello from C++!" << std::endl;
        return 0;
      }
    `);
    
    // Test LaTeX - Simple document
    await runTest('latex', `
      \\documentclass{article}
      \\begin{document}
      \\section{Hello LaTeX}
      This is a simple LaTeX document generated by the CodeRoom compiler service.
      
      \\subsection{Features}
      The service can compile:
      \\begin{itemize}
        \\item Simple documents
        \\item Mathematical equations: $E = mc^2$
        \\item And more!
      \\end{itemize}
      
      \\end{document}
    `);
    
    console.log('\nAll tests completed!');
  } catch (error) {
    console.error('Test suite failed:', error);
  }
}

// Run the tests
runTests();